# Generated by Django 4.2.7 on 2023-11-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
