# Generated by Django 4.2.7 on 2023-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_rename_user_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer')], default='applicant', max_length=20),
        ),
    ]
