# Generated by Django 4.2.7 on 2023-11-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
