# Generated by Django 4.2.7 on 2023-11-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0013_alter_job_created_by_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
