# Generated by Django 4.2.7 on 2023-11-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0018_rename_change_at_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='jobs_application',
        ),
    ]
