# Generated by Django 4.2.7 on 2023-11-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0019_alter_application_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table=None,
        ),
    ]
