# Generated by Django 4.2.7 on 2023-11-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0020_alter_application_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
