# Generated by Django 4.2.7 on 2023-11-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0022_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
