# Generated by Django 4.2.7 on 2023-11-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0023_userprofile_is_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_applicant',
        ),
    ]
